version: '3.4'

services:
  backend:
    image: backend
    build:
      context: Server
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 3001:3001
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "index.js"]
